{
    'name': 'Generate RFQ from Sales Quotation',
    'version': '19.6',
    'summary': '',
    'description': 'Create PO from SO, Create ticket from SO, Create DO from Helpdesk,Create Delivery from Sale order',
    'license': 'OPL-1',
    'category': 'Sales',
    'author': "HAK Technologies",
    'website': "http://www.haktechnologies.com",
    'images': ['static/description/icon.png'],
    'depends': ['sale_management', 'purchase', 'helpdesk', 'stock', 'helpdesk_sale_timesheet'],
    'data': [
        'security/ir.model.access.csv',
        # 'wizard/so_to_rfq_wiz_view.xml',
        # 'wizard/so_to_ticket.xml',
        # 'wizard/ticket_to_delivery_view.xml',
        # 'wizard/so_to_delivery.xml',
        # 'views/sale_order_views_inherit.xml',
        # 'views/helpdesk_views.xml',
    ],
    'installable': True,
    'auto_install': False,
}
